name: Build Mega SDK C++

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade and Download necessary files for build..
        run: bash setup.sh

      - name: build Mega SDK ..
        run: bash build.sh

      - name: tar the SDK
        run: cd "~/home/sdk/"
             tar -zcvf megasdk.tar.gz
             ls && pwd
             mkdir ~/home/releases/
             cp ~/home/sdk/megasdk.tar.gz ~/home/releases/
       
      - name: mv wheel
        run: mv ~/home/sdk/bindings/python/dist/*.whl MegaSdkC-py2.py3-none-any.whl
             cp ~/home/sdk/bindings/python/dist/*.whl ~/home/releases
 
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: false
          prerelease: false
          title: "MegaSDKC++-Python-wheel"
          files: |
            ~/home/releases/*.tar.gz
            ~/home/releases*.whl
